# Generated by Django 4.0.4 on 2022-11-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_termmodel'),
        ('quiz', '0002_alter_quizmodel_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='space.spacemodel'),
        ),
    ]
