# Generated by Django 4.0.4 on 2022-05-15 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0002_space_members_alter_space_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Space',
            new_name='SpaceModel',
        ),
    ]
